DROP TABLE IF EXISTS users_skills;
DROP TABLE IF EXISTS positions;
DROP TABLE IF EXISTS education;
DROP TABLE IF EXISTS skills;
DROP TABLE IF EXISTS followers;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(50) NOT NULL
);
CREATE TABLE education (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id integer REFERENCES users (id),
    university varchar(100) NOT NULL,
    degree varchar(50) NOT NULL,
    major varchar(100) NOT NULL,
    start_date date NOT NULL,
    end_date date
);
CREATE TABLE positions (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id integer REFERENCES users (id),
    title varchar(50) NOT NULL,
    company varchar(50) NOT NULL,
    start_date date NOT NULL,
    end_date date
);
CREATE TABLE skills (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(20) UNIQUE NOT NULL
);
CREATE TABLE users_skills (
    user_id integer REFERENCES users (id),
    skill_id integer REFERENCES skills (id),
    PRIMARY KEY (user_id, skill_id)
);

CREATE TABLE followers (
    user_id integer REFERENCES users (id),
    follower_id integer REFERENCES users (id),
    PRIMARY KEY (user_id, follower_id)
)
