DROP TABLE IF EXISTS education;
CREATE TABLE education (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER REFERENCES users (id),
    university VARCHAR(100),
    degree VARCHAR(50),
    major VARCHAR(100),
    start_date DATE,
    end_date DATE
)
