DROP TABLE IF EXISTS users_skills;
DROP TABLE IF EXISTS positions;
DROP TABLE IF EXISTS education;
DROP TABLE IF EXISTS skills;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(50)
);
CREATE TABLE education (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id integer REFERENCES users (id),
    university varchar(100),
    degree varchar(50),
    major varchar(100),
    start_date date,
    end_date date
);
CREATE TABLE positions (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id integer REFERENCES users (id),
    title varchar(50),
    company varchar(50),
    start_date date,
    end_date date
);
CREATE TABLE skills (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(20)
);
CREATE TABLE users_skills (
    user_id integer REFERENCES users (id),
    skill_id integer REFERENCES skills (id),
    PRIMARY KEY (user_id, skill_id)
);
