[project]
name = "day01-perf-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[all]>=0.116.1",
    "numpy>=2.3.2",
    "uvicorn>=0.35.0",
]
